# Generated by Django 5.2.6 on 2025-10-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
