# Generated by Django 5.2.6 on 2025-10-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payments_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='is_refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payments',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='refund_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='refund_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
