# Generated by Django 5.2.6 on 2025-10-03 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_orders_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='total_amount',
            new_name='price',
        ),
    ]
