# Generated by Django 5.2.6 on 2025-10-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_total_amount_orders_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(blank=True, default='Ordered', max_length=9, null=True),
        ),
    ]
