# Generated by Django 5.2.6 on 2025-09-19 07:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0004_cart_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.FloatField(default=0, max_length=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
