# Generated by Django 5.2.6 on 2025-10-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchants',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
